import { useEffect, useMemo, useState } from "react";
import { MapContainer, TileLayer, Circle, CircleMarker, Polyline, Popup, useMap } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertTriangle, ArrowRight, Check, ChevronRight, CloudRain, Crosshair, Droplets, ExternalLink, Flame, Gauge, HeartPulse, Info, LocateFixed, MapPin, Menu, Navigation, Phone, Radio, Route, Shield, Siren, Sparkles, Waves, Wind, X } from "lucide-react";
import { HAZARDS, MUMBAI_CENTER, ROUTES, SAMPLE_WEATHER, type RiskLevel } from "@shared/nivara";

type View = "welcome" | "overview" | "route" | "resources";
type Mode = "live" | "simulation";

const riskMeta: Record<RiskLevel, { color: string; soft: string; label: string }> = {
  LOW: { color: "#28c48a", soft: "rgba(40,196,138,.14)", label: "LOW" },
  MODERATE: { color: "#f6c453", soft: "rgba(246,196,83,.14)", label: "MODERATE" },
  HIGH: { color: "#ff914d", soft: "rgba(255,145,77,.16)", label: "HIGH" },
  CRITICAL: { color: "#f05d6c", soft: "rgba(240,93,108,.16)", label: "CRITICAL" },
};

function MapRefresher({ center }: { center: [number, number] }) {
  const map = useMap();
  useEffect(() => { map.setView(center, 12.7, { animate: true }); }, [center, map]);
  return null;
}

function RiskBadge({ level }: { level: RiskLevel }) {
  const meta = riskMeta[level];
  return <span className="risk-badge" style={{ background: meta.soft, color: meta.color }}><span className="pulse-dot" style={{ background: meta.color }} />{meta.label}</span>;
}

function Metric({ label, value, suffix, accent = "#91a4b8" }: { label: string; value: string | number; suffix?: string; accent?: string }) {
  return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value" style={{ color: accent }}>{value}<small>{suffix}</small></div></div>;
}

function RiskGauge({ score, level }: { score: number; level: RiskLevel }) {
  const meta = riskMeta[level];
  return <div className="gauge-wrap"><div className="gauge" style={{ background: `conic-gradient(${meta.color} ${score * 3.6}deg, #223043 0deg)` }}><div className="gauge-center"><strong>{score}</strong><span>/ 100</span></div></div><div className="gauge-label"><RiskBadge level={level} /><span>Current personal risk</span></div></div>;
}

type MapHazard = { id: string; type: string; severity: string; riskScore: number; description: string; center: [number, number]; radius: number };

function MapPanel({ center, simulated, routeVisible, rainfall = 82, hazards = HAZARDS }: { center: [number, number]; simulated: boolean; routeVisible: boolean; rainfall?: number; hazards?: MapHazard[] }) {
  return <div className="map-shell"><MapContainer center={center} zoom={12.7} scrollWheelZoom className="leaflet-map"><MapRefresher center={center} /><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
    <Circle center={[19.076, 72.878]} radius={4200 + rainfall * 35} pathOptions={{ color: "#58b8ff", fillColor: "#58b8ff", fillOpacity: Math.min(.11, rainfall / 1200), weight: 2, dashArray: "5 8" }}><Popup><strong>Rainfall context</strong><br />{rainfall} mm/h around Mumbai fallback</Popup></Circle>
    {hazards.map((hazard) => <Circle key={hazard.id} center={hazard.center} radius={hazard.radius * 100000} pathOptions={{ color: hazard.severity === "HIGH" ? "#ff914d" : "#f6c453", fillColor: hazard.severity === "HIGH" ? "#ff914d" : "#f6c453", fillOpacity: .18, weight: 2 }}><Popup><strong>{hazard.type} · {hazard.severity}</strong><br />Risk {hazard.riskScore}/100<br />{hazard.description}</Popup></Circle>)}
    {routeVisible && <><Polyline positions={ROUTES.current.coordinates} pathOptions={{ color: "#f05d6c", weight: 7, opacity: .9 }} /><Polyline positions={ROUTES.alternative.coordinates} pathOptions={{ color: "#28c48a", weight: 5, dashArray: "10 8", opacity: .95 }} /></>}
    <CircleMarker center={center} radius={10} pathOptions={{ color: "#fff", fillColor: simulated ? "#ff914d" : "#58b8ff", fillOpacity: 1, weight: 3 }}><Popup><strong>{simulated ? "Simulation position" : "Your location"}</strong><br />Mumbai · GPS fallback ready</Popup></CircleMarker>
  </MapContainer><div className="map-legend"><span><i className="legend-dot flood" />High flood zone</span><span><i className="legend-dot moderate" />Moderate zone</span><span><i className="legend-weather" />Rainfall context</span>{routeVisible && <><span><i className="legend-line danger" />Current route</span><span><i className="legend-line safe" />Safer route</span></>}</div><div className="map-attribution">Live map · OpenStreetMap</div></div>;
}

function Landing({ onSelect }: { onSelect: (mode: Mode) => void }) { return <main className="landing"><div className="landing-grid"><div className="landing-copy"><div className="brand landing-brand"><div className="brand-mark"><Waves size={19} /></div><div><strong>NIVARA</strong><span>Personal risk intelligence</span></div></div><div className="eyebrow"><span className="eyebrow-line" />PERSONAL DISASTER DECISION SUPPORT</div><h1>Know the risk.<br /><em>Choose what’s next.</em></h1><p>NIVARA turns weather, hazards, and route context into a clear personal safety picture for Mumbai.</p><div className="landing-proof"><span><Check size={14} />Explainable scoring</span><span><MapPin size={14} />Mumbai-ready</span><span><Shield size={14} />Official warnings first</span></div></div><div className="mode-picker"><div className="card-kicker">CHOOSE YOUR VIEW</div><h2>How would you like to begin?</h2><p>Use a live location when available, or walk through a realistic flood scenario.</p><button className="mode-card" onClick={() => onSelect("live")}><div className="mode-card-icon live"><LocateFixed size={20} /></div><div><strong>Live situation</strong><span>Use location, weather, and nearby hazards</span></div><ArrowRight size={17} /></button><button className="mode-card" onClick={() => onSelect("simulation")}><div className="mode-card-icon sim"><Radio size={20} /></div><div><strong>Flood simulation</strong><span>Explore LOW → CRITICAL decision points</span></div><ArrowRight size={17} /></button><div className="landing-note"><Info size={14} />Works with cached Mumbai demo data if live services are unavailable.</div></div></div><div className="landing-footer"><span>Built for clearer decisions in severe weather</span><span>Leaflet · OpenStreetMap · Explainable risk engine</span></div></main>; }

function Topbar({ mode, setMode, onMenu }: { mode: Mode; setMode: (v: Mode) => void; onMenu: () => void }) {
  return <header className="topbar"><div className="brand"><div className="brand-mark"><Waves size={19} /></div><div><strong>NIVARA</strong><span>Personal risk intelligence</span></div></div><div className="topbar-center"><div className="status-pill"><span className="status-live" />Systems nominal</div><span className="topbar-time">22 Aug 2026 · 13:41 IST</span></div><div className="topbar-actions"><Tabs value={mode} onValueChange={(v) => setMode(v as Mode)}><TabsList className="mode-tabs"><TabsTrigger value="live"><LocateFixed size={14} />Live</TabsTrigger><TabsTrigger value="simulation"><Radio size={14} />Simulate</TabsTrigger></TabsList></Tabs><Button variant="ghost" size="icon" className="mobile-menu" onClick={onMenu}><Menu size={19} /></Button><div className="avatar">AR</div></div></header>;
}

function Sidebar({ view, setView, mode, open, close }: { view: View; setView: (v: View) => void; mode: Mode; open: boolean; close: () => void }) {
  const items = [{ id: "overview" as View, icon: Gauge, label: "Risk overview" }, { id: "route" as View, icon: Route, label: "Route risk" }, { id: "resources" as View, icon: HeartPulse, label: "Emergency resources" }];
  return <aside className={`sidebar ${open ? "open" : ""}`}><div className="sidebar-head"><span>COMMAND CENTER</span><Button variant="ghost" size="icon" className="mobile-close" onClick={close}><X size={18} /></Button></div><nav>{items.map(({ id, icon: Icon, label }) => <button key={id} className={`nav-item ${view === id ? "active" : ""}`} onClick={() => { setView(id); close(); }}><Icon size={17} /><span>{label}</span>{view === id && <ChevronRight size={15} className="nav-arrow" />}</button>)}</nav><div className="sidebar-spacer" /><div className="sidebar-footer"><div className="location-row"><MapPin size={16} /><div><strong>Mumbai, IN</strong><span>Fallback location active</span></div></div><div className="sidebar-note"><Info size={15} /><span>Guidance is informational. Follow official emergency instructions first.</span></div></div></aside>;
}

function Overview({ mode, simulationStep, setSimulationStep, location, setView, locationStatus, locationUpdatedAt, onUseFallback, offline }: { mode: Mode; simulationStep: number; setSimulationStep: (v: number) => void; location: [number, number]; setView: (v: View) => void; locationStatus: string; locationUpdatedAt: string; onUseFallback: (preset?: string) => void; offline: boolean }) {
  // Live mode: real weather + real risk score from the FastAPI risk engine, at the user's GPS/fallback location.
  const weatherQuery = trpc.weather.useQuery({ lat: location[0], lng: location[1] }, { enabled: mode === "live" });
  const riskQuery = trpc.risk.useQuery({ lat: location[0], lng: location[1] }, { enabled: mode === "live" });
  const hazardsQuery = trpc.hazards.useQuery();
  const hazards = hazardsQuery.data?.hazards ?? HAZARDS;

  // Simulation mode: same risk engine, scripted position + rainfall curve from the backend.
  const simulationQuery = trpc.simulation.useQuery({ step: simulationStep }, { enabled: mode === "simulation" });

  const weather = mode === "simulation" ? (simulationQuery.data?.weather ?? SAMPLE_WEATHER) : (weatherQuery.data ?? SAMPLE_WEATHER);
  const fallbackRisk = { score: 0, level: "LOW" as RiskLevel, reasons: [] as string[], alert: "", recommendation: "Waiting for risk data…", summary: "" };
  const risk = mode === "simulation" ? (simulationQuery.data?.risk ?? fallbackRisk) : (riskQuery.data ?? fallbackRisk);
  const dataUnavailable = mode === "simulation" ? simulationQuery.isError : riskQuery.isError || weatherQuery.isError;

  const [running, setRunning] = useState(false);
  useEffect(() => { if (!running || mode !== "simulation") return; const timer = window.setInterval(() => setSimulationStep(simulationStep >= 3 ? 0 : simulationStep + 1), 2600); return () => window.clearInterval(timer); }, [running, mode, simulationStep, setSimulationStep]);
  const mapCenter = mode === "simulation" ? (simulationQuery.data?.location ?? location) : location;
  const future = mode === "simulation" ? [risk.score, Math.min(100, risk.score + 10), Math.min(100, risk.score + 19)] : [54, 67, 84];
  return <>
    <section className="page-intro"><div><div className="eyebrow"><span className="eyebrow-line" />{mode === "simulation" ? "SIMULATION CONTROL" : "LIVE SITUATIONAL AWARENESS"}</div><h1>{mode === "simulation" ? "Flood scenario" : "Good afternoon, Aisha."}</h1><p>{mode === "simulation" ? "Observe how the same risk engine responds as your simulated location moves through affected zones." : "A clear picture of what is happening around you — and what to do next."}</p></div><div className="location-chip"><Crosshair size={15} /><div><strong>{mode === "simulation" ? "Simulated position" : "Mumbai, Maharashtra"}</strong><span>{mode === "simulation" ? `Scenario point ${simulationStep + 1} of 4` : `${location[0].toFixed(4)}° N · ${location[1].toFixed(4)}° E · ${locationUpdatedAt}`}</span></div>{mode === "live" && <select className="fallback-select" aria-label="Choose manual Mumbai location" defaultValue="fallback" onChange={(e) => onUseFallback(e.target.value)}><option value="fallback">Mumbai fallback</option><option value="bkc">BKC · flood zone</option><option value="dadar">Dadar West</option><option value="south">South Mumbai</option></select>}</div></section>
    {offline && <div className="offline-banner" role="status"><Info size={15} />You are offline. NIVARA is showing cached Mumbai conditions so the demonstration can continue.</div>}
    {(mode === "live" ? (weatherQuery.isLoading || riskQuery.isLoading) : simulationQuery.isLoading) && <div className="data-strip"><CloudRain size={14} />Refreshing weather and risk context...</div>}
    {dataUnavailable && <div className="data-strip warning"><Info size={14} />Live risk engine unavailable. Showing cached sample conditions.</div>}
    {risk.level === "HIGH" || risk.level === "CRITICAL" ? <div className="alert-banner" role="alert"><div className="alert-icon"><Siren size={20} /></div><div><strong>{risk.level === "CRITICAL" ? "Critical risk detected" : "High risk detected nearby"}</strong><span>{risk.alert} Official warnings always take priority.</span></div><Button className="alert-action" onClick={() => setView("route")}>Review safer route <ArrowRight size={15} /></Button></div> : null}
    <div className="dashboard-grid"><Card className="risk-card"><CardHeader><div><div className="card-kicker">CURRENT RISK</div><CardTitle>Personal exposure</CardTitle></div><RiskBadge level={risk.level} /></CardHeader><CardContent><div className="risk-card-main"><RiskGauge score={risk.score} level={risk.level} /><div className="risk-reasons"><div className="section-label">Why this score</div>{risk.reasons.slice(0, 4).map((reason) => <div className="reason" key={reason}><Check size={14} />{reason}</div>)}</div></div><div className="recommendation"><Sparkles size={16} /><div><span>Recommended action</span><strong>{risk.recommendation}</strong></div></div></CardContent></Card>
      <Card className="weather-card"><CardHeader><div><div className="card-kicker">WEATHER NOW</div><CardTitle>{weather.condition}</CardTitle></div><CloudRain className="weather-icon" size={25} /></CardHeader><CardContent><div className="weather-temp">{weather.temperature}<sup>°</sup><span>C</span></div><div className="weather-stats"><Metric label="Rainfall" value={weather.rainfall} suffix=" mm/h" accent="#58b8ff" /><Metric label="Wind" value={weather.wind} suffix=" km/h" accent="#a9b9cc" /><Metric label="Rain chance" value={weather.precipitationProbability} suffix="%" accent="#a9b9cc" /></div><div className="forecast"><div className="section-label">Rain forecast</div>{weather.forecast.map((item) => <div className="forecast-item" key={item.time}><span>{item.time}</span><CloudRain size={14} /><strong>{item.value}%</strong></div>)}</div></CardContent></Card>
      <Card className="map-card"><CardHeader><div><div className="card-kicker">HAZARD MAP</div><CardTitle>What’s around you</CardTitle></div><span className="map-updated"><span className="status-live" />Updated 2 min ago</span></CardHeader><CardContent className="map-content"><MapPanel center={mapCenter} simulated={mode === "simulation"} routeVisible={false} rainfall={weather.rainfall} hazards={hazards} /></CardContent></Card>
      <Card className="future-card"><CardHeader><div><div className="card-kicker">FUTURE RISK</div><CardTitle>How risk may change</CardTitle></div><span className="muted-label">Forecast horizon</span></CardHeader><CardContent><div className="timeline">{future.map((value, i) => { const level = value <= 30 ? "LOW" : value <= 60 ? "MODERATE" : value <= 80 ? "HIGH" : "CRITICAL"; return <div className="timeline-point" key={i}><div className="timeline-value" style={{ color: riskMeta[level].color }}>{value}</div><div className="timeline-track"><span style={{ width: `${value}%`, background: riskMeta[level].color }} /></div><div className="timeline-time">{i === 0 ? "NOW" : `+${i} HOUR`}</div><RiskBadge level={level} /></div>; })}</div><p className="future-note"><Wind size={14} />Rainfall intensity is expected to peak within the next two hours.</p></CardContent></Card>
    </div>
    <div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" />ACTIVE HAZARDS</div><h2>Signals worth knowing</h2></div><button className="text-link" onClick={() => setView("route")}>Open route analysis <ArrowRight size={15} /></button></div>
    <div className="hazard-grid">{hazards.slice(0, 3).map((hazard) => <Card className="hazard-card" key={hazard.id}><CardContent><div className="hazard-top"><div className={`hazard-symbol ${hazard.severity.toLowerCase()}`}><Droplets size={17} /></div><RiskBadge level={hazard.severity as RiskLevel} /></div><h3>{hazard.type}</h3><p>{hazard.description}</p><div className="hazard-meta"><span><MapPin size={13} />{hazard.center[0].toFixed(3)}° N</span><span>{hazard.status}</span></div></CardContent></Card>)}</div>
    {mode === "simulation" && <Card className="simulation-card"><CardContent><div className="simulation-copy"><div className="card-kicker">DEMO SCENARIO</div><h2>Move through the storm</h2><p>Advance the sample position through Mumbai’s flood zones to demonstrate the complete LOW → CRITICAL progression.</p></div><div className="simulation-controls"><div className="sim-progress"><span>Scenario progress</span><strong>{simulationStep + 1} / 4</strong></div><Progress value={(simulationStep + 1) * 25} /><div className="sim-buttons"><Button onClick={() => setRunning(!running)} className="primary-button">{running ? "Pause simulation" : "Start simulation"}<ArrowRight size={16} /></Button><Button variant="outline" onClick={() => setSimulationStep(simulationStep >= 3 ? 0 : simulationStep + 1)}>Next step</Button></div></div></CardContent></Card>}
  </>;
}

function RouteView({ location }: { location: [number, number] }) {
  const [destination, setDestination] = useState("Bandra Kurla Complex");
  const routeMutation = trpc.routeRisk.useMutation();
  const hazardsQuery = trpc.hazards.useQuery();
  const hazards = hazardsQuery.data?.hazards ?? HAZARDS;
  const routeData = routeMutation.data ?? { ...ROUTES, destination, recommendation: "Alternative Route B is recommended because the current route passes through a high-risk flood zone." };
  return <>{routeMutation.isError && <div className="data-strip warning" role="alert"><Info size={14} />Route analysis is unavailable right now. Showing the cached Mumbai route comparison.</div>}<section className="page-intro"><div><div className="eyebrow"><span className="eyebrow-line" />ROUTE RISK ANALYSIS</div><h1>Travel with more context.</h1><p>See how hazards intersect your route before you leave.</p></div><div className="safe-pill"><Shield size={16} />Safer route available</div></section><Card className="route-search"><CardContent><div className="route-field"><MapPin size={17} /><div><span>START LOCATION</span><strong>Current location · {location[0].toFixed(4)}, {location[1].toFixed(4)}</strong></div></div><ArrowRight className="route-arrow" size={17} /><div className="route-field destination-field"><Navigation size={17} /><div><span>DESTINATION</span><input value={destination} onChange={(e) => setDestination(e.target.value)} aria-label="Destination" /></div></div><Button className="primary-button" onClick={() => routeMutation.mutate({ destination })}>{routeMutation.isPending ? "Analyzing..." : "Analyze route"}<ArrowRight size={16} /></Button></CardContent></Card><div className="route-layout"><Card className="route-map-card"><CardHeader><div><div className="card-kicker">ROUTE OVERLAY</div><CardTitle>{destination}</CardTitle></div><span className="map-updated"><span className="status-live" />Prototype analysis</span></CardHeader><CardContent className="map-content"><MapPanel center={location} simulated={false} routeVisible rainfall={82} hazards={hazards} /></CardContent></Card><div className="route-options"><RouteOption route={routeData.current} danger /><RouteOption route={routeData.alternative} /><Card className="recommendation-card"><CardContent><div className="recommendation"><Sparkles size={16} /><div><span>Route recommendation</span><strong>{routeData.recommendation}</strong><small>Current route exposes you to {routeData.current.exposed}% of a high-risk flood zone. The alternative adds 3 minutes and reduces exposure to {routeData.alternative.exposed}%.</small></div></div></CardContent></Card></div></div></>;
}

function RouteOption({ route, danger = false }: { route: typeof ROUTES.current; danger?: boolean }) { return <Card className={`route-option ${danger ? "danger-route" : "safe-route"}`}><CardContent><div className="route-option-head"><div><div className="route-name"><span className={`route-radio ${danger ? "danger" : "safe"}`} />{route.name}</div><span className="route-time">{route.duration} · {route.distance}</span></div><RiskBadge level={route.severity} /></div><div className="route-risk-line"><div><span>Route risk</span><strong>{route.risk}<small>/100</small></strong></div><div><span>Exposed</span><strong>{route.exposed}%</strong></div><div><span>Peak hazard</span><strong>{route.severity}</strong></div></div><Progress value={route.risk} /></CardContent></Card>; }

function Resources() { const resources = [{ icon: Phone, label: "Emergency services", value: "112", detail: "National emergency number", accent: "#f05d6c" }, { icon: Flame, label: "Fire & rescue", value: "101", detail: "Mumbai Fire Brigade", accent: "#ff914d" }, { icon: HeartPulse, label: "Ambulance", value: "108", detail: "Emergency medical response", accent: "#58b8ff" }, { icon: Shield, label: "Mumbai Police", value: "100", detail: "Police control room", accent: "#a890ff" }]; const places = [{ icon: HeartPulse, title: "Sion Hospital", type: "Hospital · 2.4 km", status: "Open 24 hours" }, { icon: Shield, title: "BKC Relief Shelter", type: "Shelter · 1.8 km", status: "Capacity available" }, { icon: Flame, title: "Bandra Fire Station", type: "Fire services · 3.1 km", status: "Response ready" }]; return <><section className="page-intro"><div><div className="eyebrow"><span className="eyebrow-line" />EMERGENCY RESOURCES</div><h1>Help, when it matters.</h1><p>Keep essential contacts and nearby support within reach.</p></div><div className="safe-pill"><Shield size={16} />Verified sample directory</div></section><div className="resource-grid">{resources.map(({ icon: Icon, label, value, detail, accent }) => <Card className="resource-card" key={label}><CardContent><div className="resource-icon" style={{ color: accent, background: `${accent}1a` }}><Icon size={19} /></div><span>{label}</span><strong>{value}</strong><small>{detail}</small><button className="call-link">Call now <Phone size={13} /></button></CardContent></Card>)}</div><div className="section-heading resources-heading"><div><div className="eyebrow"><span className="eyebrow-line" />NEARBY SUPPORT</div><h2>Places that can help</h2></div><span className="muted-label">Based on Mumbai fallback location</span></div><div className="places-grid">{places.map(({ icon: Icon, title, type, status }) => <Card className="place-card" key={title}><CardContent><div className="place-icon"><Icon size={18} /></div><div><h3>{title}</h3><p>{type}</p><span className="place-status"><span className="status-live" />{status}</span></div><ExternalLink size={16} className="place-open" /></CardContent></Card>)}</div><div className="official-note"><Info size={17} /><div><strong>Important safety note</strong><p>NIVARA recommendations are informational and cannot replace official emergency warnings. If authorities issue an evacuation or shelter instruction, follow it immediately.</p></div></div></>; }

export default function Home() {
  const [view, setView] = useState<View>("welcome");
  const [mode, setMode] = useState<Mode>("live");
  const [simulationStep, setSimulationStep] = useState(0);
  const [location, setLocation] = useState<[number, number]>([MUMBAI_CENTER.lat, MUMBAI_CENTER.lng]);
  const [locationStatus, setLocationStatus] = useState("Last known Mumbai location");
  const [locationUpdatedAt, setLocationUpdatedAt] = useState("timestamp pending");
  const [offline, setOffline] = useState(() => !navigator.onLine);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  useEffect(() => { const cached = localStorage.getItem("nivara:last-known-location"); if (cached) { try { setLocation(JSON.parse(cached)); setLocationStatus("Last known GPS location"); } catch { /* Ignore malformed fallback cache. */ } } const online = () => setOffline(false); const offlineEvent = () => setOffline(true); window.addEventListener("online", online); window.addEventListener("offline", offlineEvent); if (!navigator.geolocation) { setLocationStatus("Live location unavailable · using Mumbai fallback"); return () => { window.removeEventListener("online", online); window.removeEventListener("offline", offlineEvent); }; } const watcher = navigator.geolocation.watchPosition((position) => { setLocation([position.coords.latitude, position.coords.longitude]); localStorage.setItem("nivara:last-known-location", JSON.stringify([position.coords.latitude, position.coords.longitude])); setLocationStatus(`GPS · ±${Math.round(position.coords.accuracy)}m accuracy`); setLocationUpdatedAt(new Date(position.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })); }, () => setLocationStatus("Permission denied · using Mumbai fallback"), { enableHighAccuracy: true, maximumAge: 30000 }); return () => { navigator.geolocation.clearWatch(watcher); window.removeEventListener("online", online); window.removeEventListener("offline", offlineEvent); }; }, []);
  if (view === "welcome") return <Landing onSelect={(selectedMode) => { setMode(selectedMode); setView("overview"); }} />;
  const content = view === "overview" ? <Overview mode={mode} simulationStep={simulationStep} setSimulationStep={setSimulationStep} location={location} setView={setView} locationStatus={locationStatus} locationUpdatedAt={locationUpdatedAt} onUseFallback={(preset = "fallback") => { const points: Record<string, [number, number]> = { fallback: [MUMBAI_CENTER.lat, MUMBAI_CENTER.lng], bkc: [19.067, 72.868], dadar: [19.018, 72.842], south: [18.96, 72.83] }; const next = points[preset] ?? points.fallback; setLocation(next); localStorage.setItem("nivara:last-known-location", JSON.stringify(next)); setLocationStatus(`Manual location · ${preset === "fallback" ? "Mumbai fallback" : preset.toUpperCase()}`); setLocationUpdatedAt(new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })); }} offline={offline} /> : view === "route" ? <RouteView location={location} /> : <Resources />;
  return <div className="app-shell"><Topbar mode={mode} setMode={(v) => { setMode(v); setView("overview"); }} onMenu={() => setSidebarOpen(true)} /><Sidebar view={view} setView={setView} mode={mode} open={sidebarOpen} close={() => setSidebarOpen(false)} /><main className="main-content">{content}<footer className="app-footer"><span><span className="status-live" />{locationStatus}</span><span>Prototype data · Last synced 2 min ago</span></footer></main>{sidebarOpen && <div className="mobile-overlay" onClick={() => setSidebarOpen(false)} />}</div>;
}
